package xenocosm
package phonology

import xenocosm.phonology.data._

/**
  * Lookups for X-SAMPA
  *
  * @see http://www.phon.ucl.ac.uk/home/sampa/x-sampa.htm
  * @see http://www.phon.ucl.ac.uk/home/sampa/ipasam-x.pdf
  * @see https://en.wikipedia.org/wiki/X-SAMPA
  */
object XSAMPA {

  val pulmonics: Map[Pulmonic, String] = Map(
    Pulmonic(Voiceless, Bilabial, Plosive) →                "p",
    Pulmonic(Voiced, Bilabial, Plosive) →                   "b",
    Pulmonic(Voiceless, LabioDental, Plosive) →             "p_d",
    Pulmonic(Voiced, LabioDental, Plosive) →                "b_d",
    Pulmonic(Voiceless, Dental, Plosive) →                  "t",
    Pulmonic(Voiced, Dental, Plosive) →                     "d",
    Pulmonic(Voiceless, Alveolar, Plosive) →                "t",
    Pulmonic(Voiced, Alveolar, Plosive) →                   "d",
    Pulmonic(Voiceless, PostAlveolar, Plosive) →            "t",
    Pulmonic(Voiced, PostAlveolar, Plosive) →               "d",
    Pulmonic(Voiceless, Retroflex, Plosive) →               "t`",
    Pulmonic(Voiced, Retroflex, Plosive) →                  "d`",
    Pulmonic(Voiceless, Palatal, Plosive) →                 "c",
    Pulmonic(Voiced, Palatal, Plosive) →                    "J\\",
    Pulmonic(Voiceless, Velar, Plosive) →                   "k",
    Pulmonic(Voiced, Velar, Plosive) →                      "g",
    Pulmonic(Voiceless, Uvular, Plosive) →                  "q",
    Pulmonic(Voiced, Uvular, Plosive) →                     "G\\",
    Pulmonic(Voiceless, Pharyngeal, Plosive) →              ">\\",
    Pulmonic(Voiceless, Glottal, Plosive) →                 "?",

    Pulmonic(Voiceless, Bilabial, Nasal) →                  "m",
    Pulmonic(Voiced, Bilabial, Nasal) →                     "m",
    Pulmonic(Voiceless, LabioDental, Nasal) →               "F",
    Pulmonic(Voiced, LabioDental, Nasal) →                  "F",
    Pulmonic(Voiceless, Dental, Nasal) →                    "n",
    Pulmonic(Voiced, Dental, Nasal) →                       "n",
    Pulmonic(Voiceless, Alveolar, Nasal) →                  "n",
    Pulmonic(Voiced, Alveolar, Nasal) →                     "n",
    Pulmonic(Voiceless, PostAlveolar, Nasal) →              "n",
    Pulmonic(Voiced, PostAlveolar, Nasal) →                 "n",
    Pulmonic(Voiceless, Retroflex, Nasal) →                 "n`",
    Pulmonic(Voiced, Retroflex, Nasal) →                    "n`",
    Pulmonic(Voiceless, Palatal, Nasal) →                   "J",
    Pulmonic(Voiced, Palatal, Nasal) →                      "J",
    Pulmonic(Voiceless, Velar, Nasal) →                     "N",
    Pulmonic(Voiced, Velar, Nasal) →                        "N",
    Pulmonic(Voiceless, Uvular, Nasal) →                    "N\\",
    Pulmonic(Voiced, Uvular, Nasal) →                       "N\\",

    Pulmonic(Voiceless, Bilabial, Trill) →                  "B\\",
    Pulmonic(Voiced, Bilabial, Trill) →                     "B\\",
    Pulmonic(Voiceless, LabioDental, Trill) →               "B\\_d",
    Pulmonic(Voiced, LabioDental, Trill) →                  "B\\_d",
    Pulmonic(Voiceless, Dental, Trill) →                    "r",
    Pulmonic(Voiced, Dental, Trill) →                       "r",
    Pulmonic(Voiceless, Alveolar, Trill) →                  "r",
    Pulmonic(Voiced, Alveolar, Trill) →                     "r",
    Pulmonic(Voiceless, PostAlveolar, Trill) →              "r",
    Pulmonic(Voiced, PostAlveolar, Trill) →                 "r",
    Pulmonic(Voiceless, Uvular, Trill) →                    "R\\",
    Pulmonic(Voiced, Uvular, Trill) →                       "R\\",

    Pulmonic(Voiceless, Dental, TapOrFlap) →                "4",
    Pulmonic(Voiced, Dental, TapOrFlap) →                   "4",
    Pulmonic(Voiceless, Alveolar, TapOrFlap) →              "4",
    Pulmonic(Voiced, Alveolar, TapOrFlap) →                 "4",
    Pulmonic(Voiceless, PostAlveolar, TapOrFlap) →          "4",
    Pulmonic(Voiced, PostAlveolar, TapOrFlap) →             "4",
    Pulmonic(Voiceless, Retroflex, TapOrFlap) →             "r`",
    Pulmonic(Voiced, Retroflex, TapOrFlap) →                "r`",

    Pulmonic(Voiceless, Bilabial, Fricative) →              "p\\",
    Pulmonic(Voiced, Bilabial, Fricative) →                 "B",
    Pulmonic(Voiceless, LabioDental, Fricative) →           "f",
    Pulmonic(Voiced, LabioDental, Fricative) →              "v",
    Pulmonic(Voiceless, Dental, Fricative) →                "T",
    Pulmonic(Voiced, Dental, Fricative) →                   "D",
    Pulmonic(Voiceless, Alveolar, Fricative) →              "s",
    Pulmonic(Voiced, Alveolar, Fricative) →                 "z",
    Pulmonic(Voiceless, PostAlveolar, Fricative) →          "S",
    Pulmonic(Voiced, PostAlveolar, Fricative) →             "Z",
    Pulmonic(Voiceless, Retroflex, Fricative) →             "s`",
    Pulmonic(Voiced, Retroflex, Fricative) →                "z`",
    Pulmonic(Voiceless, Palatal, Fricative) →               "C",
    Pulmonic(Voiced, Palatal, Fricative) →                  "j\\",
    Pulmonic(Voiceless, Velar, Fricative) →                 "x",
    Pulmonic(Voiced, Velar, Fricative) →                    "G",
    Pulmonic(Voiceless, Uvular, Fricative) →                "X",
    Pulmonic(Voiced, Uvular, Fricative) →                   "R",
    Pulmonic(Voiceless, Pharyngeal, Fricative) →            "X\\",
    Pulmonic(Voiced, Pharyngeal, Fricative) →               "?\\",
    Pulmonic(Voiceless, Glottal, Fricative) →               "h",
    Pulmonic(Voiced, Glottal, Fricative) →                  "h\\",

    Pulmonic(Voiceless, Dental, LateralFricative) →         "K",
    Pulmonic(Voiced, Dental, LateralFricative) →            "K\\",
    Pulmonic(Voiceless, Alveolar, LateralFricative) →       "K",
    Pulmonic(Voiced, Alveolar, LateralFricative) →          "K\\",
    Pulmonic(Voiceless, PostAlveolar, LateralFricative) →   "K",
    Pulmonic(Voiced, PostAlveolar, LateralFricative) →      "K\\",

    Pulmonic(Voiceless, Bilabial, Approximant) →            "B_o",
    Pulmonic(Voiced, Bilabial, Approximant) →               "B_o",
    Pulmonic(Voiceless, LabioDental, Approximant) →         "v\\",
    Pulmonic(Voiced, LabioDental, Approximant) →            "v\\",
    Pulmonic(Voiceless, Dental, Approximant) →              "r\\",
    Pulmonic(Voiced, Dental, Approximant) →                 "r\\",
    Pulmonic(Voiceless, Alveolar, Approximant) →            "r\\",
    Pulmonic(Voiced, Alveolar, Approximant) →               "r\\",
    Pulmonic(Voiceless, PostAlveolar, Approximant) →        "r\\",
    Pulmonic(Voiced, PostAlveolar, Approximant) →           "r\\",
    Pulmonic(Voiceless, Retroflex, Approximant) →           "r\\`",
    Pulmonic(Voiced, Retroflex, Approximant) →              "r\\`",
    Pulmonic(Voiceless, Palatal, Approximant) →             "j",
    Pulmonic(Voiced, Palatal, Approximant) →                "j",
    Pulmonic(Voiceless, Velar, Approximant) →               "M\\",
    Pulmonic(Voiced, Velar, Approximant) →                  "M\\",
    Pulmonic(Voiced, Uvular, Approximant) →                 "R",
    Pulmonic(Voiced, Pharyngeal, Approximant) →             "?\\",

    Pulmonic(Voiceless, Dental, LateralApproximant) →       "l",
    Pulmonic(Voiced, Dental, LateralApproximant) →          "l",
    Pulmonic(Voiceless, Alveolar, LateralApproximant) →     "l",
    Pulmonic(Voiced, Alveolar, LateralApproximant) →        "l",
    Pulmonic(Voiceless, PostAlveolar, LateralApproximant) → "l",
    Pulmonic(Voiced, PostAlveolar, LateralApproximant) →    "l",
    Pulmonic(Voiceless, Retroflex, LateralApproximant) →    "l`",
    Pulmonic(Voiced, Retroflex, LateralApproximant) →       "l`",
    Pulmonic(Voiceless, Palatal, LateralApproximant) →      "L",
    Pulmonic(Voiced, Palatal, LateralApproximant) →         "L",
    Pulmonic(Voiceless, Velar, LateralApproximant) →        "L\\",
    Pulmonic(Voiced, Velar, LateralApproximant) →           "L\\"
  )

  val vowels: Map[Vowel, String] = Map(
    Vowel(Unrounded, Close, Front) →                        "i",
    Vowel(Rounded, Close, Front) →                          "y",
    Vowel(Unrounded, Close, Central) →                      "1",
    Vowel(Rounded, Close, Central) →                        "}",
    Vowel(Unrounded, Close, Back) →                         "M",
    Vowel(Rounded, Close, Back) →                           "u",

    Vowel(Unrounded, NearClose, NearFront) →                "I",
    Vowel(Rounded, NearClose, NearFront) →                  "Y",
    Vowel(Unrounded, NearClose, Central) →                  "I\\",
    Vowel(Rounded, NearClose, Central) →                    "U\\",
    Vowel(Rounded, NearClose, NearBack) →                   "U",

    Vowel(Unrounded, CloseMid, Front) →                     "e",
    Vowel(Rounded, CloseMid, Front) →                       "2",
    Vowel(Unrounded, CloseMid, Central) →                   "@\\",
    Vowel(Rounded, CloseMid, Central) →                     "8",
    Vowel(Unrounded, CloseMid, Back) →                      "7",
    Vowel(Rounded, CloseMid, Back) →                        "o",

    Vowel(Unrounded, Mid, Central) →                        "@",
    Vowel(Rounded, Mid, Central) →                          "@",

    Vowel(Unrounded, OpenMid, Front) →                      "E",
    Vowel(Rounded, OpenMid, Front) →                        "9",
    Vowel(Unrounded, OpenMid, Central) →                    "3",
    Vowel(Rounded, OpenMid, Central) →                      "3\\",
    Vowel(Unrounded, OpenMid, Back) →                       "V",
    Vowel(Rounded, OpenMid, Back) →                         "O",

    Vowel(Unrounded, NearOpen, Front) →                     "{",
    Vowel(Unrounded, NearOpen, Central) →                   "6",
    Vowel(Rounded, NearOpen, Central) →                     "6",

    Vowel(Unrounded, Open, Front) →                         "a",
    Vowel(Rounded, Open, Front) →                           "&",
    Vowel(Unrounded, Open, Back) →                          "A",
    Vowel(Rounded, Open, Back) →                            "Q"
  )
}
