language: scala
jdk: openjdk8
scala:
   - 2.12.2

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/331d8714a9dc9a4c14c6
    on_success: change
    on_failure: always
    on_start: never

before_deploy:
 - sbt universal:packageBin

deploy:
  - provider: s3
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: xenocosm-release
    skip_cleanup: true
    local_dir: target/universal
  - provider: codedeploy
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: xenocosm-release
    key: xenocosm.zip
    application: xenocosm
    deployment_group: xenocosm-live-deploy
    on:
      branch: release
