language: scala
jdk: openjdk8
scala:
   - 2.12.5

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.2.8 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1

script:
 - sbt ++$TRAVIS_SCALA_VERSION validate

after_success:
  - bash <(curl -s https://codecov.io/bash)
