sudo: required
language: scala
jdk:
  - openjdk8

scala:
  - 2.12.7

services:
  - docker

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/decrypt-keys.sh; fi
  - export PATH=${PATH}:./vendor/bundle
  - npm install dredd@5.2.0 --no-optional --global

install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION validate
  - sbt ++$TRAVIS_SCALA_VERSION makeMicrosite

after_success:
  - dredd ./xenocosm.apib http://127.0.0.1 --dry-run
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishMicrosite.sh; fi

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  skip_cleanup: true
  provider: script
  script: sbt http/docker:publish
  on:
    tags: true
