FORMAT: 1A
HOST: https://xenocosm.com/

# Xenocosm API v0

Xenocosm is a space-trader played exclusively through this API.

## Authentication [/auth]

### Authenticate (Basic Auth) [POST]

A simple auth API, probably not the final one.

+ Request

    Currently, any non-empty username in the Basic Auth credentials will result
    in success. This will change in the future.

    + Headers

            Authorization: Basic Zm9vOmJhcg==

+ Response 303

    Sets a cookie which will be used as an authentication token for subsequent
    requests. The location header will either be to `/trader` if the identity
    has no trader selected, or to some location in the multiverse if there is a
    trader (`/verse/:universe/:galaxy/:star/:planet`).

    + Headers

            Location: /

+ Response 401

    On any error.

    + Headers

            WWW-Authenticate: Basic realm="xenocosm"

### Check auth token [HEAD]

This can be used as a "heartbeat" to avoid the session timing out.

+ Response 204

    Any valid auth cookie will have its expiration reset.

+ Response 401

    If there is no auth token.

    + Headers

            WWW-Authenticate: Basic realm="xenocosm"

### Revoke auth token [DELETE]

While not explicitly required, one may often need to "log out". This is how we
do it.

+ Response 204

    Explicitly removes the cookie.

## Traders [/trader]

### List Traders for an Identity [GET]

+ Response 200 (application/hal+json)

### Create and select a Trader for an Identity [POST]

+ Response 201 (application/hal+json)

## Trader [/trader/{trader_id}]

+ Parameters
    + trader_id: AAAAAAAAAAAAAAAAAAAAAA (string) - ID of the Trader, a 22-character string representing a base64-encoded UUID

### Show a Trader [GET]

+ Response 200 (application/hal+json)

+ Response 404

    If the Trader does not exist.

### Select a Trader for an Identity [POST]

+ Response 200 (application/hal+json)

+ Response 404

    If the Trader does not exist.

### Delete and deselect a Trader [DELETE]

+ Response 204

## Universe [/verse/{universe_id}]

+ Parameters
    + universe_id: AAAAAAAAAAAAAAAAAAAAAA (string) - ID of the Universe, a 22-character string representing a base64-encoded UUID

### Show Universe [GET]

+ Response 200 (application/hal+json)

+ Response 401

    If the current trader is not located in this universe.

## Galaxy [/verse/{universe_id}/{x0},{y0},{z0}]

+ Parameters
    + universe_id: AAAAAAAAAAAAAAAAAAAAAA (string) - ID of the Universe, a 22-character string representing a base64-encoded UUID
    + x0: `-1` (number) - The X-coordinate within the universe in multiples of 10k parsecs
    + y0: `-1` (number) - The Y-coordinate within the universe in multiples of 10k parsecs
    + z0:  `0` (number) - The Z-coordinate within the universe in multiples of 10k parsecs

### Show Galaxy [GET]

+ Response 200 (application/hal+json)

+ Response 401

    If the current trader is not located in this galaxy.

## Star System [/verse/{universe_id}/{x0},{y0},{z0}/{x1},{y1},{z1}]

+ Parameters
    + universe_id: AAAAAAAAAAAAAAAAAAAAAA (string) - ID of the Universe, a 22-character string representing a base64-encoded UUID
    + x0: `-1` (number) - The X-coordinate within the universe in multiples of 10k parsecs
    + y0: `-1` (number) - The Y-coordinate within the universe in multiples of 10k parsecs
    + z0:  `0` (number) - The Z-coordinate within the universe in multiples of 10k parsecs
    + x1:  `0` (number) - The X-coordinate within the galaxy in whole parsecs
    + y1: `-1` (number) - The Y-coordinate within the galaxy in whole parsecs
    + z1:  `0` (number) - The Z-coordinate within the galaxy in whole parsecs

### Show Star [GET]

+ Response 200 (application/hal+json)

+ Response 401

    If the current trader is not located in this star system.

## Planet [/verse/{universe_id}/{x0},{y0},{z0}/{x1},{y1},{z1}/{x2},{y2},{z2}]

+ Parameters
    + universe_id: AAAAAAAAAAAAAAAAAAAAAA (string) - ID of the Universe, a 22-character string representing a base64-encoded UUID
    + x0: `-1` (number) - The X-coordinate within the universe in multiples of 10k parsecs
    + y0: `-1` (number) - The Y-coordinate within the universe in multiples of 10k parsecs
    + z0:  `0` (number) - The Z-coordinate within the universe in multiples of 10k parsecs
    + x1:  `0` (number) - The X-coordinate within the galaxy in whole parsecs
    + y1: `-1` (number) - The Y-coordinate within the galaxy in whole parsecs
    + z1:  `0` (number) - The Z-coordinate within the galaxy in whole parsecs
    + x2: `-1` (number) - The X-coordinate within the star system in whole astronomical units
    + y2:  `0` (number) - The Y-coordinate within the star system in whole astronomical units
    + z2: `-1` (number) - The Z-coordinate within the star system in whole astronomical units

### Show Planet [GET]

+ Response 200 (application/hal+json)

+ Response 401

    If the current trader is not located at this planet.
