version: 0.0
os: linux
files:
  - source: bin
    destination: /usr/local/bin
  - source: lib
    destination: /usr/local/lib
  - source: deploy/xenocosm.service
    destination: /etc/systemd/system
hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy/application_stop.sh
      timeout: 300
      runas: root
