addSbtPlugin("org.scalastyle"  %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"         % "1.5.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"               % "0.9.3")
addSbtPlugin("com.47deg"        % "sbt-microsites"        % "0.7.16")
addSbtPlugin("com.eed3si9n"     % "sbt-unidoc"            % "0.4.1")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"         % "0.8.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"   % "1.3.3")
